//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otelUcusAppProject.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotels
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> location { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<decimal> priceperadult { get; set; }
        public Nullable<decimal> priceperchild { get; set; }
    
        public virtual amounthotel amounthotel { get; set; }
        public virtual locations locations { get; set; }
        public virtual reservation_services reservation_services { get; set; }
    }
}
