//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otelUcusAppProject.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation_services
    {
        public int reservation_id { get; set; }
        public int service_id { get; set; }
    
        public virtual flights flights { get; set; }
        public virtual hotels hotels { get; set; }
        public virtual reservations reservations { get; set; }
    }
}
